# database init, supports mysql too
database=mariadb
spring.datasource.url=jdbc:mariadb://localhost:3306/CATLab_db
spring.datasource.username=root
spring.datasource.password=m4ri4db_r00t
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
